### ISSUE TITLE
이미지 Null 처리

### ISSUE THREAD

**Issue by choidam** [yourCozy/cozy-iOS#69]
효율적인 방법으로 이미지 null 값 처리해보기..!

**Comment by didwodnr123** [comment]
이거 제가 해결했습니다.

객체에서 이미지 값들만 뽑아서 따로 배열을 만들고

self.displayDetailList = [self.detailData[0].image2 ?? "", self.detailData[0].image3 ?? "", self.detailData[0].image4 ?? "", self.detailData[0].image5 ?? "", self.detailData[0].image6 ?? "", self.detailData[0].image7 ?? "", self.detailData[0].image8 ?? "", self.detailData[0].image9 ?? "", self.detailData[0].image10 ?? ""]

self.displayDetailList = self.displayDetailList.filter {$0 != ""} 이걸로 배열에 있는 값 필터링해서 제거해주면~ 됩니다

**Comment by didwodnr123** [comment]
@choidam

**Comment by didwodnr123** [comment]
아 이거말고,, 회색 이미지 어떻게 처리할지 얘기한건가....
