### ISSUE TITLE
활동 선택에서 이미지 Or UIView touch Event

### ISSUE THREAD

**Issue by didwodnr123** [yourCozy/cozy-iOS#72]
touch event

gestureHandler?

아직 어떻게 하는지 잘 모르겠다.. 버튼만 구현되어 있는 상태이다

**Comment by choidam** [comment]
@didwodnr123 `UITapGestureRecognizer` 사용 추천드립니다.
LoginVC 에서 로그인 버튼을 모두 UIView 로 만들어서 이벤트 그걸로 추가했어요.
냠냠 하세여

**Comment by didwodnr123** [comment]
> @didwodnr123 `UITapGestureRecognizer` 사용 추천드립니다.
> LoginVC 에서 로그인 버튼을 모두 UIView 로 만들어서 이벤트 그걸로 추가했어요.
> 냠냠 하세여

제스처로 시도해봤는데 카카오, 애플 로그인 2개의 뷰 같은 경우에는 각각 다른 액션으로 넘겨주면 되지만,,

활통탭의 버튼들은 모두 같은뷰로 넘어가고 ❗️activityIdx를 전달해줘야 다음 뷰에서 통신으로 데이터를 뽑아올  수 있어요..

그래서 버튼같은 경우 1~20까지 Tag를 붙여서 태그 값을 activityIdx로 해서 넘겨줬는데 뷰는 어떻게 넘겨야 하는지 찾아봐야해요ㅜㅜ
