### ISSUE TITLE
활동 탭에서 request error 남

### ISSUE THREAD

**Issue by choidam** [yourCozy/cozy-iOS#94]
@didwodnr123 확인해주세여 ㅜㅜ 모두 조회 안 됨

**Comment by didwodnr123** [comment]
네 ㅎ학인해보겠습니다!

**Comment by didwodnr123** [comment]
> @didwodnr123 확인해주세여 ㅜㅜ 모두 조회 안 됨

이거 그냥 데이터가 없어서 못받아오는거에요!

**Comment by didwodnr123** [comment]
데이터가 있으면! 제대로 들어온답니다!
